// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"RESTAPIPOSTGIN/dbConfig"
	"RESTAPIPOSTGIN/handler"
	"RESTAPIPOSTGIN/repository"
	"RESTAPIPOSTGIN/service"
)

// Injectors from wire.go:

func InitializeHandler() (*handler.UserHandler, error) {
	db, err := dbconfig.NewDB()
	if err != nil {
		return nil, err
	}
	userRepo := repository.NewUserRepo(db)
	userService := service.NewUserService(userRepo)
	userHandler := handler.NewUserHandler(userService)
	return userHandler, nil
}
