// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"WireDI/Project/handler"
	"WireDI/Project/repository"
	"WireDI/Project/service"
)

// Injectors from wire.go:
func InitializeUserHandler() *handler.UserHandler {
	userRepo := repository.NewUserRepo()
	userService := service.NewUserService(userRepo)
	userHandler := handler.NewUserHandler(userService)
	return userHandler
}
